---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: amazon-prime-clone
  labels:
    app: amazon-prime-clone
spec:
  replicas: 2
  selector:
    matchLabels:
      app: amazon-prime-clone
  template:
    metadata:
      labels:
        app: amazon-prime-clone
    spec:
      containers:
      - name: amazon-prime-clone-container
        image: bettysami/amazon-prime-clone:latest
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        env:
        - name: NODE_ENV
          value: "production"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
