---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: amazon-prime-clone
  labels:
    app: amazon-prime-clone
spec:
  replicas: 2
  selector:
    matchLabels:
      app: amazon-prime-clone
  template:
    metadata:
      labels:
        app: amazon-prime-clone
    spec:
      containers:
      - name: amazon-prime-clone-container
        image: bettysami/amazon-prime-clone:latest
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "256Mi"
            cpu: "150m"
          limits:
            memory: "512Mi"
            cpu: "300m"
        env:
        - name: NODE_ENV
          value: "production"
        # Temporarily remove health checks for dev server
        # livenessProbe:
        #   httpGet:
        #     path: /
        #     port: 3000
        #   initialDelaySeconds: 60
        #   periodSeconds: 10
        # readinessProbe:
        #   httpGet:
        #     path: /
        #     port: 3000
        #   initialDelaySeconds: 30
        #   periodSeconds: 5