---
apiVersion: v1
kind: Service
metadata:
  name: amazon-prime-clone-service
  labels:
    app: amazon-prime-clone
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: amazon-prime-clone
  type: LoadBalancer
