clusterName: "amazon-prime-opensearch"
nodeGroup: "master"
replicas: 1

# Disable security completely
securityConfig:
  enabled: false

opensearchConfiguration:
  opensearch.yml: |
    cluster.name: amazon-prime-opensearch
    network.host: 0.0.0.0
    plugins.security.disabled: true
    discovery.type: single-node

# Conservative resources for t3.medium
resources:
  requests:
    cpu: "200m"
    memory: "512Mi"
  limits:
    cpu: "1000m"
    memory: "1Gi"

# Smaller heap
opensearchJavaOpts: "-Xmx512m -Xms512m"

persistence:
  enabled: true
  size: 10Gi
  storageClass: "gp2"
