replicas: 1

esConfig:
  elasticsearch.yml: |
    cluster.name: "amazon-prime-logs"
    network.host: 0.0.0.0
    discovery.type: single-node
    xpack.security.enabled: false

resources:
  requests:
    cpu: "500m"
    memory: "1Gi"
  limits:
    cpu: "1000m"
    memory: "2Gi"

volumeClaimTemplate:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: "gp2"
  resources:
    requests:
      storage: 10Gi

service:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 9200
    - name: transport
      protocol: TCP
      port: 9300

# This prevents the automatic master nodes setting
masterService: ""
